version: '3.9'

services:
  mysql:
    image: mysql:8
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=soteria
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_HOST=localhost
  web:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - mysql